on:
  pull_request:
  workflow_dispatch: # Allow manual triggering

jobs:
  versiontag:
    name: Validate version bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pvarki/config-ci-library/.github/actions/validate-bumpversion@main

  pre_commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: j178/prek-action@v2

  docker_builds:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build test target
        run: docker build --target configs -t nginx-templates:test .
      - name: Build production target
        run: docker build --target production -t nginx-server:test .

  publish_nginx:
    name: Publish NGinx Docker image
    needs: [versiontag, pre_commit, docker_builds]
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Publish Docker image
        uses: pvarki/config-ci-library/.github/actions/publish-image@main
        with:
          product: nginx
          component: server
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          acr-repo: ${{ vars.ACR_REPO }}
          acr-username: ${{ vars.ACR_USERNAME }}
          acr-token: ${{ secrets.ACR_TOKEN }}

  publish_templates:
    name: Publish templates Docker image
    needs: [versiontag, pre_commit, docker_builds]
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Publish Docker image
        uses: pvarki/config-ci-library/.github/actions/publish-image@main
        with:
          product: nginx-templates
          component: worker
          target: configs
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          acr-repo: ${{ vars.ACR_REPO }}
          acr-username: ${{ vars.ACR_USERNAME }}
          acr-token: ${{ secrets.ACR_TOKEN }}
